# Generated by Django 4.1.5 on 2023-03-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logregapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
