# Generated by Django 4.1.5 on 2023-03-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Address", models.CharField(max_length=100, verbose_name="Address")),
                ("Latitude", models.FloatField(default=0, verbose_name="Latitude")),
                ("Longitude", models.FloatField(default=0, verbose_name="Longitude")),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CarModel", models.CharField(max_length=100, verbose_name="CarModel")),
                ("Engine", models.CharField(max_length=50, verbose_name="Engine")),
                ("BodyType", models.CharField(max_length=100, verbose_name="BodyType")),
                ("Capacity", models.IntegerField(default=4, verbose_name="Capacity")),
                ("Fuel", models.CharField(max_length=50, verbose_name="Fuel")),
                (
                    "Transmission",
                    models.CharField(max_length=50, verbose_name="Transmission"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_menu.address",
                    ),
                ),
            ],
        ),
    ]
