# Generated by Django 4.1.5 on 2023-03-27 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="car", name="address",),
        migrations.AddField(
            model_name="car",
            name="Photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/car_photos"
            ),
        ),
        migrations.CreateModel(
            name="TakenCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_taken", models.DateField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_menu.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="Address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_menu.address",
            ),
        ),
    ]
